### PR TITLE
New: Testing with lower bound requirements

### PR DESCRIPTION
**Pull request by jistr**
We started testing with two OpenStack SDK versions:

* 0.52.x which is close to latest but not yet affected by a security
  group rules bug [1].

* 0.36.x which is in Train release (OSP 16).

[1] https://storyboard.openstack.org/#!/story/2008577

### CODE REVIEW

**Comment by jistr** [comment]
The first e2e 10->16 is expected to fail -- we're now using the lower bound reqs file but the compatibility bug isn't fixed yet. Once we see the job fail here, i'll push another commit that should fix it.

**Comment by jistr** [comment]
```
    AttributeError: 'Image' object has no attribute 'owner'
```

Yup the job failed as expected (as reported in #343 ). I'll push another commit to try and fix it.

**Comment by jistr** [comment]
It works :)

**Review by odyssey4me — APPROVED** [review]
